version: "3.8"

services: 

  nginx: 
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/www:/www
    ports:
      - 80:80

  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  python-api: 
    build: ./microservices/python
    # container_name: api
    hostname: python-api
    restart: always
    volumes:
      - ./microservices/python/scripts:/app
    ports:
      - 5000
    environment: 
      FLASK_APP: /app/script.py
    deploy:
      mode: replicated
      replicas: 2

  nodejs-api: 
    build: ./microservices/nodejs
    # container_name: api
    hostname: nodejs-api
    restart: always
    volumes:
      - ./microservices/nodejs/scripts:/app
    ports:
      - 5000
    deploy:
      mode: replicated
      replicas: 2

  rust-api:
    build: ./microservices/rust
    # container_name: api
    hostname: rust-api
    restart: always
    volumes:
      - ./microservices/rust/scripts:/app
    ports:
      - 5000
    deploy:
      mode: replicated
      replicas: 2
